# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCduhofHCfuhhVrdKkihem4O3xQxqc4H
"""



!pip install requests beautifulsoup4 openpyxl

import requests
from bs4 import BeautifulSoup
import openpyxl

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Books"
ws.append(["Title", "Price", "Rating", "Availability"])

rating_map = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}

base_url = "https://books.toscrape.com/catalogue/"
url = "https://books.toscrape.com/catalogue/page-1.html"

page = 1
while url:
    print(f"Scraping page {page}...")
    response = requests.get(url)
    response.encoding = "utf-8"  # ✅ Fix for £ symbol
    soup = BeautifulSoup(response.text, "html.parser")
    books = soup.find_all("article", class_="product_pod")

    for book in books:
        title = book.h3.a["title"]
        price = book.find("p", class_="price_color").text.strip()
        rating_word = book.p["class"][1]
        rating = rating_map.get(rating_word, 0)
        availability = book.find("p", class_="instock availability").text.strip()
        ws.append([title, price, rating, availability])

    next_btn = soup.find("li", class_="next")
    if next_btn:
        url = base_url + next_btn.a["href"]
        page += 1
    else:
        url = None

wb.save("/content/books_data.xlsx")
print(f"✅ Done! Scraped {page} pages. 1000 books saved.")

from google.colab import files
files.download("/content/books_data.xlsx")